### ISSUE TITLE
rem voor font-sizes

### ISSUE THREAD

**Issue by vasilisvg** [MartijnNieuwenhuizen/css-to-the-rescue#1]
Waarom gebruik je eigenlijk `rem` voor font-size? Er zitten een paar nadelen aan, zoals je hier kan lezen: https://vasilis.nl/nerd/dislike-rem-unit/
Voor andere onderdelen is de `rem` weer uitermate geschikt: https://vasilis.nl/nerd/use-em-rem-right-use-cases/

**Comment by MartijnNieuwenhuizen** [comment]
Dank voor je artikelen, dit geeft een opheldering. font-size { rem --> em };
