### ISSUE TITLE
KIKKE!

### ISSUE THREAD

**Issue by vasilisvg** [MartijnNieuwenhuizen/css-to-the-rescue#5]
Wat tof dit. Ik ben heel benieuwd naar je bevindingen!
https://github.com/MartijnNieuwenhuizen/CSS-to-the-Rescue/blob/master/Week%201/css/style.css#L383

**Comment by vasilisvg** [comment]
Werkt ook prima op een Blackberry Playbook.

**Comment by MartijnNieuwenhuizen** [comment]
Ja, het is behoorlijk vet!
In deze video: https://developers.google.com/web/updates/2014/03/Get-on-the-CSS-Grid, legt iemand van Chrome het principe best goed uit. 

Maar tot nu toe lijkt het in mijn ogen op flexibele tabels. Nu mag ik hier niet heel veel over zeggen aangezien ik nooit echt met tabels heb hoeven werken.
